[API-1501] Refactor for removing unneeded operations. (#1005)
hazelcast/hazelcast-cpp-client pull request #1027
Opened 2022-10-28 09:17 UTC by OzanCansel

- Removed assert statement.
- If there is an entry then emplace fails so I changed it to something like 'upsert' operation. If the entry is already there I just update the 'session_state' to the brand-new one.

Fixes #1005

2022-10-28 09:55 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-10-28 10:07 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-18 12:01 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-18 12:02 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 08:41 UTC, ihsandemir requested changes
Looks good.

Is there a unit test? If missing, can we add a test?

2022-11-25 08:41 UTC, ihsandemir commented on hazelcast/src/hazelcast/cp/cp_impl.cpp
> +        result.first->second = state;
```suggestion
    if(!result.second) {
        result.first->second = session_state state { response.id , response.ttl_millis };
   }
```
Can you use move operator and add move assignment operator instead?

2022-11-25 09:13 UTC, OzanCansel commented
> Looks good.
> 
> Is there a unit test? If missing, can we add a test?

Yes it is already written at [here](https://github.com/hazelcast/hazelcast-cpp-client/blob/master/hazelcast/test/src/HazelcastTests8.cpp#L1827)

2022-11-25 12:32 UTC, ihsandemir approved these changes

2022-11-25 13:31 UTC, merged