generate-docs target added to CMake. It will preprocess the readme.
hazelcast/hazelcast-cpp-client pull request #1036
Opened 2022-11-16 16:49 UTC by OzanCansel

- `generate-docs` target added to CMake.
- It will preprocess the readme.md and generates the doxygen docs.

It basically converts the relative links to absolute urls.

2022-11-16 17:27 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-16 19:43 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-17 05:51 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-17 06:25 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-17 06:26 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-17 07:09 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-24 15:03 UTC, ihsandemir requested changes
The following does not work in MacOS:

`scripts/generate-docs.sh README.md 5.1  "https://github.com/hazelcast/hazelcast-cpp-client"`

2022-11-24 16:33 UTC, OzanCansel commented on CMakeLists.txt
> +if ( UNIX )
I only targeted linux systems and didn't think that it needs to be a cross-platform script(s). It is easier to port to `MacOS` but do we really need to port to `Windows` ?

2022-11-24 16:34 UTC, OzanCansel commented on scripts/generate-docs.sh
> +MAINPAGE=${1}
Let me add

2022-11-25 06:15 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 06:33 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 07:46 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 08:13 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 08:31 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 09:32 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 12:05 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 12:37 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 14:21 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 14:50 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 14:55 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-25 14:58 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 16:01 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-25 16:37 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-28 08:21 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-28 08:57 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-28 08:59 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-28 09:03 UTC, OzanCansel commented
Ported to MacOS. `grep` and `doxygen` are needed to be installed.

```sh
brew install grep doxygen
```

2022-11-28 09:05 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-28 09:37 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-28 10:21 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-11-28 11:11 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-11-28 11:53 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-11 20:09 UTC, closed without merging