Forward declaration was done starting from hazelcast_client.h
hazelcast/hazelcast-cpp-client pull request #1053
Opened 2022-12-18 01:12 UTC by cngzhnp

There are a lot of nested header files which most of might not be needed to include. So, I clean up a little bit starting from hazelcast_client.h file. If acceptable, I could try a little bit more because it takes too much time build & link it.

2022-12-18 01:12 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-12-18 01:12 UTC, devOpsHazelcast commented
Can one of the admins verify this patch?

2022-12-28 08:00 UTC, OzanCansel commented
Root cause of long compile time is boost library itself. See [here](https://github.com/hazelcast/hazelcast-cpp-client/issues/1034). It is possible to reduce compile time with forward declaration for the files which use boost but are not exposed in header files. But `boost::future<T>` is already exposed in public api and it includes 150-160k lines of code by itself.

So probably forward declaration will not be worthwhile.

However, I will run PR builders and will check your PR. Even it doesn't noticably decrease compile time, it is a good practise to use forward declaration technique wherever it is possible.

2022-12-28 08:01 UTC, OzanCansel commented
verify

2022-12-28 08:49 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-28 11:18 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-29 07:00 UTC, OzanCansel requested changes
It compiles without the lines I suggested to remove. Could you make changes?

2023-02-05 15:15 UTC, cngzhnp commented on hazelcast/src/hazelcast/client/spi.cpp
> +#include "hazelcast/client/internal/nearcache/NearCacheManager.h"
Done.

2023-02-05 15:16 UTC, cngzhnp commented on hazelcast/src/hazelcast/client/proxy.cpp
> +#include "hazelcast/client/spi/impl/ClientPartitionServiceImpl.h"
Done.

2023-02-05 15:17 UTC, cngzhnp commented on hazelcast/include/hazelcast/client/ringbuffer/read_result_set.h
> +#include "hazelcast/client/serialization/serialization.h"
Done.

2023-02-05 15:17 UTC, cngzhnp commented on hazelcast/include/hazelcast/client/transaction_context.h
> +#include "hazelcast/client/spi/ClientContext.h"
Done.

2023-02-05 15:17 UTC, cngzhnp commented on hazelcast/include/hazelcast/client/reliable_topic.h
> +}
Done.

2023-02-05 15:18 UTC, cngzhnp commented on hazelcast/include/hazelcast/client/proxy/ReplicatedMapImpl.h
> +#include "hazelcast/client/entry_event.h"
Done.

2023-02-05 15:18 UTC, cngzhnp commented on hazelcast/include/hazelcast/client/impl/hazelcast_client_instance_impl.h
> +class reliable_topic;
Done.

2023-02-05 15:20 UTC, cngzhnp commented
@OzanCansel Could you please verify that your changes are completed?

2023-02-06 08:56 UTC, OzanCansel commented
Thanks for changes, I will run PR builders again.

verify

2023-02-06 08:57 UTC, OzanCansel commented
verify

2023-02-06 09:38 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-02-06 09:45 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-02-07 11:17 UTC, akeles85 reviewed
Changes seem ok.

I want to share my results with compile time of library without tests and examples. In my laptop, the compile time takes like below:

1 job:
    Before change: 1 minute 25 seconds
    After change: 1 minute 24 seconds

6 paralel jobs (-j 6):
    Before change: 20 seconds
    After change: 20 seconds

By the way, precompiled headers might be also a good option to consider.

2023-03-02 07:21 UTC, OzanCansel commented
verify

2023-03-02 07:22 UTC, OzanCansel approved these changes

2023-03-02 08:12 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-03-02 08:39 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-03-02 11:38 UTC, merged