5.0.0 references replaced with 5.1.0
hazelcast/hazelcast-cpp-client pull request #1057
Opened 2022-12-20 13:57 UTC by OzanCansel

2022-12-20 14:35 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-20 14:59 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-20 15:12 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-20 15:26 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 07:01 UTC, yuce requested changes
Looks good, a few ideas...

2022-12-21 07:19 UTC, OzanCansel commented on Reference_Manual.md
> +This chapter provides information on how you can use Hazelcast's data structures in the C++ client, after giving some basic information including an overview to the client API, operation modes of the
Fixed.

2022-12-21 07:21 UTC, OzanCansel commented on Reference_Manual.md
> +Hazelcast Command Line is a tool which allows users to install & run Hazelcast and Management Center on local environment. Please follow the [Command Line Tool Instructions](https://github.com/hazelc
Fixed.

2022-12-21 07:37 UTC, OzanCansel commented on Reference_Manual.md
>  Nov 19, 2020 2:52:59 PM com.hazelcast.internal.cluster.ClusterService
Fixed.

2022-12-21 07:39 UTC, OzanCansel commented on Reference_Manual.md
> +See the [Hazelcast Reference Manual](https://docs.hazelcast.com/hazelcast/latest/getting-started.html) for more information on setting up the clusters.
Fixed.

2022-12-21 07:53 UTC, yuce approved these changes
Looks good!

2022-12-21 08:46 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 08:46 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 09:34 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 09:45 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 09:57 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-21 10:22 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 10:34 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-21 10:48 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 10:59 UTC, yuce approved these changes

2022-12-21 11:12 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-21 11:49 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-21 11:54 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 12:06 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 12:23 UTC, devOpsHazelcast commented
Linux test FAILed.

2022-12-21 12:26 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-21 12:49 UTC, devOpsHazelcast commented
Linux test FAILed.

2022-12-21 12:49 UTC, devOpsHazelcast commented
Linux test FAILed.

2022-12-21 12:49 UTC, devOpsHazelcast commented
Linux test FAILed.

2022-12-21 12:49 UTC, devOpsHazelcast commented
Linux test FAILed.

2022-12-21 12:50 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 12:50 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 12:50 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 12:50 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 12:51 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 12:51 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 12:52 UTC, devOpsHazelcast commented
Windows test FAILed.

2022-12-21 13:28 UTC, devOpsHazelcast commented
Windows test PASSed.

2022-12-21 13:39 UTC, devOpsHazelcast commented
Linux test PASSed.

2022-12-21 14:32 UTC, merged