Compact compiler error on MacOs
hazelcast/hazelcast-cpp-client pull request #1106
Opened 2023-02-23 10:22 UTC by akeles85

After compact merge, client was not able to compile on Macos. This PR contains changes to compile it on MacOs.

2023-02-23 12:16 UTC, OzanCansel submitted a review, later dismissed

2023-02-23 12:20 UTC, devOpsHazelcast commented
Windows test FAILed.

2023-02-23 12:23 UTC, devOpsHazelcast commented
Linux test FAILed.

2023-02-24 07:37 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-02-24 08:18 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-02-24 08:29 UTC, OzanCansel requested changes

2023-02-24 08:29 UTC, OzanCansel commented on hazelcast/test/src/HazelcastTests2.cpp
> +class serializatation_test_base : public testing::Test
```suggestion
class serialization_test_base : public testing::Test
```

2023-02-24 08:29 UTC, OzanCansel commented on hazelcast/test/src/HazelcastTests2.cpp
> +class ClientSerializationTest : public ClientTest
```suggestion
class ClientSerializationTest : public serialization_test_base
```

2023-02-24 08:37 UTC, akeles85 commented on hazelcast/test/src/HazelcastTests2.cpp
> +class ClientSerializationTest : public ClientTest
fixed

2023-02-24 08:37 UTC, akeles85 commented on hazelcast/test/src/HazelcastTests2.cpp
> +class serializatation_test_base : public testing::Test
fixed

2023-02-24 08:48 UTC, OzanCansel approved these changes

2023-02-24 09:11 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-02-24 09:14 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-02-24 09:27 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-02-24 09:33 UTC, merged