version is updated to 5.2.0
hazelcast/hazelcast-cpp-client pull request #1154
Opened 2023-03-13 06:13 UTC by akeles85

Version is updated to 5.2.0

2023-03-13 07:03 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-03-13 07:11 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-03-13 09:09 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-03-13 15:43 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-03-13 16:03 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-03-13 17:20 UTC, OzanCansel requested changes
Could you replace `5.1.0` on `Reference_Manual.md` file ?

2023-03-14 06:02 UTC, akeles85 commented
> Could you replace `5.1.0` on `Reference_Manual.md` file ?

Do you mean the log outputs? I did not change them consciously. I think they are temporary outputs, it would be better not to change. What do you say?

2023-03-14 06:46 UTC, akeles85 commented
> Could you replace `5.1.0` on `Reference_Manual.md` file ?

5.1.0 in logs is updated as 5.x.x

2023-03-14 07:25 UTC, OzanCansel approved these changes

2023-03-14 07:35 UTC, devOpsHazelcast commented
Linux test PASSed.

2023-03-14 08:02 UTC, devOpsHazelcast commented
Windows test PASSed.

2023-03-14 13:02 UTC, merged