Use non-SNAPSHOT hazelcast dependencies
hazelcast/hazelcast-cpp-client pull request #1207
Opened 2023-08-07 19:42 UTC by JackPGreen

To ensure future build reproducibility, use production-released dependencies over SNAPSHOT builds.

2023-08-07 19:59 UTC, devOpsHazelcast commented
Linux test FAILed.

2023-08-14 18:32 UTC, devOpsHazelcast commented
Linux test FAILed.

2023-09-13 09:24 UTC, devOpsHazelcast commented
Linux test FAILed.

2023-12-14 00:59 UTC, devOpsHazelcast commented
PR closed by Hazelcast automation as no activity (>3 months). Please reopen with comments, if necessary. Thank you for using Hazelcast and your valuable contributions

2023-12-14 06:13 UTC, JackPGreen commented
Reopen

2023-12-14 06:53 UTC, devOpsHazelcast commented
Linux test FAILed.

2024-03-14 22:00 UTC, devOpsHazelcast commented
PR closed by Hazelcast automation as no activity (>3 months). Please reopen with comments, if necessary. Thank you for using Hazelcast and your valuable contributions

2024-07-18 21:30 UTC, devOpsHazelcast commented
PR closed by Hazelcast automation as no activity (>3 months). Please reopen with comments, if necessary. Thank you for using Hazelcast and your valuable contributions

2024-08-02 15:41 UTC, avtarraikmo requested changes
Can we update to 5.5.0?

2024-08-02 15:43 UTC, JackPGreen commented on .github/hazelcast-config.yml
> +hazelcast-version: "5.3.7"
> can we review and update to 5.5.0?


I can do, but unless [this PR is unblocked](https://github.com/hazelcast/hazelcast-cpp-client/issues/1222) (it's been open nearly a year) there's no point.

2024-08-22 11:33 UTC, JackPGreen commented
Done in https://github.com/hazelcast/hazelcast-cpp-client/pull/1231

2024-08-22 11:33 UTC, closed without merging