Add support to reading fragmented messages
hazelcast/hazelcast-cpp-client pull request #655
Opened 2020-10-15 15:12 UTC by ihsandemir

Added the support to read fragmented messages.

Also removed unused API ClientConfig::addListener(MembershipListener *listener).

2020-10-16 10:55 UTC, sancar commented
Can we add a test for it? It would be better to verify this. Since the member does not send any fragmented messages, you probably need to implement split logic also. 
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageEncoderDecoderTest.java#L299

2020-10-16 12:58 UTC, yemreinci requested changes

2020-10-16 12:58 UTC, yemreinci commented on hazelcast/src/hazelcast/client/protocol.cpp
>                              }
What happens if a message has 3 or more fragments? We are handling messages either with BEGIN_FRAGMENT_FLAG or END_FRAGMENT_FRAGMENT set but what about the middle ones?

2020-10-16 12:58 UTC, yemreinci commented on hazelcast/src/hazelcast/client/protocol.cpp
> +                auto found = partialMessages.find(msg->getCorrelationId());
Do the intermediate and the end message fragments have the correlationId? I'm looking at the protocol doc, and as far as I understand, only the first frame of the message contain the correlationId.
Shouldn't we use the fragment id to match fragments of the same message?

2020-10-23 22:09 UTC, devOpsHazelcast commented
Windows test FAILed.

2020-10-23 22:40 UTC, devOpsHazelcast commented
Linux test PASSed.

2020-10-24 12:58 UTC, devOpsHazelcast commented
Windows test FAILed.

2020-10-24 12:59 UTC, devOpsHazelcast commented
Linux test PASSed.

2020-10-26 08:29 UTC, sancar approved these changes

2020-10-26 10:40 UTC, devOpsHazelcast commented
Linux test PASSed.

2020-10-26 10:53 UTC, devOpsHazelcast commented
Windows test PASSed.

2020-10-26 15:08 UTC, yemreinci approved these changes

2020-10-26 16:06 UTC, merged