Remove the `iexecutor_service` methods using the callbacks, remove user executor, remove ResponseProcessor/
hazelcast/hazelcast-cpp-client pull request #756
Opened 2021-01-13 14:17 UTC by ihsandemir

Removed the `iexecutor_service` methods using the callbacks. It is not needed anymore, since the new boost future API provides the functionality with future continuations.

* Removed the user executor.

* Removed the unneeded ResponseThread, and associated response thread count property.

2021-01-13 14:19 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-13 14:47 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-13 14:54 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-13 14:58 UTC, ihsandemir commented
verify-linux

2021-01-13 15:23 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-13 15:32 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-13 17:35 UTC, yemreinci requested changes

2021-01-13 17:35 UTC, yemreinci commented on README.md
>  #### 7.6.1.7 Selecting Members for Task Execution
```suggestion
#### 7.6.1.6 Selecting Members for Task Execution
```

2021-01-13 19:18 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-13 19:31 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 07:11 UTC, yemreinci approved these changes

2021-01-14 08:13 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-14 08:25 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 08:36 UTC, merged