Add `hazelcast::new_client()` and `hazelcast::new_client(client_config)` to create new clients - Make `hazelcast_client` constructor private
hazelcast/hazelcast-cpp-client pull request #757
Opened 2021-01-13 19:26 UTC by ihsandemir

Added the free functions `hazelcast::new_client()` and `hazelcast::new_client(client_config)` to create new clients without using the constructor. The `hazelcast_client` constructor is made as private so that the users will be forced to use the free factory functions to create and start new clients.

2021-01-13 19:50 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-13 20:51 UTC, devOpsHazelcast commented
Windows test FAILed.

2021-01-14 05:49 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-14 06:02 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 08:40 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-14 08:42 UTC, devOpsHazelcast commented
Windows test FAILed.

2021-01-14 08:56 UTC, ihsandemir commented
verify-linux

2021-01-14 08:59 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-14 09:56 UTC, sancar approved these changes

2021-01-14 10:15 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 11:17 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-14 11:17 UTC, ihsandemir commented
verify-linux

2021-01-14 11:45 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-14 15:21 UTC, yemreinci requested changes
I've written suggestions for some of them but there are still many more indentation mistakes in the README.

2021-01-14 15:21 UTC, yemreinci commented on README.md
> +config.get_network_config().add_address(address("192.168.1.10", 5701));
```suggestion
    config.get_network_config().add_address(address("192.168.1.10", 5701));
```

2021-01-14 15:21 UTC, yemreinci commented on README.md
> +auto hz = hazelcast::new_client(std::move(config)).get(); // Connects to the cluster member at ip address `192.168.1.10` and port 5701
```suggestion
    auto hz = hazelcast::new_client(std::move(config)).get(); // Connects to the cluster member at ip address `192.168.1.10` and port 5701
```

2021-01-14 15:21 UTC, yemreinci commented on README.md
> +std::cout << "Started the Hazelcast C++ client instance " << hz.get_name() << std::endl; // Prints client instance name
```suggestion
    auto hz = hazelcast::new_client().get(); // Connects to the cluster
    std::cout << "Started the Hazelcast C++ client instance " << hz.get_name() << std::endl; // Prints client instance name
```

2021-01-14 15:21 UTC, yemreinci commented on README.md
> +auto hz = hazelcast::new_client().get(); // Connects to the cluster
```suggestion
    auto hz = hazelcast::new_client().get(); // Connects to the cluster
```

2021-01-14 15:21 UTC, yemreinci commented on README.md
> +auto personnel = hz.get_map("personnel_map").get();
```suggestion
    auto personnel = hz.get_map("personnel_map").get();
```

2021-01-14 15:21 UTC, yemreinci commented on README.md
> +hazelcast::client::auto client = hazelcast::new_client().get();
```suggestion
    auto client = hazelcast::new_client().get();
```

2021-01-14 15:23 UTC, yemreinci commented
A question: Now that the client creation is also asynchronous, would it ever make sense to set `client_connection_strategy_config::set_async_start(true)`?

2021-01-14 16:50 UTC, ihsandemir commented on hazelcast/include/hazelcast/client/hazelcast_client.h
> +    boost::future<client::hazelcast_client> HAZELCAST_API new_client();
added declaration above.

2021-01-14 16:50 UTC, ihsandemir commented on hazelcast/include/hazelcast/client/hazelcast_client.h
> +    * Note: client_config will be moved.
Removed the line. It was unnecessary since the API is explaining all it is needed.

2021-01-14 17:45 UTC, ihsandemir commented
> A question: Now that the client creation is also asynchronous, would it ever make sense to do `client_connection_strategy_config::set_async_start(true)`?

There is a slight difference, in start_async mode, the `new_client(std::move(config)).get()` may return without any connection to cluster(if any invocation during the time it connects e.g. get_map, it will throw client_offline_exception), while in the other mode it will wait to connect to the cluster. This will work similar also during reconnections. Hence, there is a slight difference. May not be a very useful feature but this is a PM (@burakcelebi ) decision to remove it or not i guess.

2021-01-14 17:48 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-14 17:55 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-14 18:00 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 18:38 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 19:11 UTC, devOpsHazelcast commented
Windows test FAILed.

2021-01-14 19:17 UTC, ihsandemir commented
verify-windows

2021-01-14 19:31 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-14 19:42 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-14 20:28 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 21:05 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-15 05:04 UTC, ihsandemir commented
verify-linux

2021-01-15 05:29 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-15 10:36 UTC, yemreinci approved these changes

2021-01-15 10:38 UTC, merged