Update README sections for installing and linking
hazelcast/hazelcast-cpp-client pull request #758
Opened 2021-01-14 19:58 UTC by yemreinci

This PR updates the sections about how to install and link against the library.

2021-01-14 20:06 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-14 21:42 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 22:19 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-14 22:58 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-15 12:16 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-15 12:27 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-15 13:29 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-15 13:31 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-15 13:41 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-15 13:53 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-15 14:48 UTC, devOpsHazelcast commented
Windows test FAILed.

2021-01-15 15:08 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-15 15:25 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-15 15:29 UTC, ihsandemir requested changes

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +* `WITH_OPENSSL` : Set to `ON` to build the library with SSL support.
It has the default value documented. It is on the next line. 👇

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +download the source code for the latest Hazelcast C++ client.
Added the "git clone checkout" alternative.

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +curl -Lo hazelcast-cpp-client-4.0.0.tar.gz https://github.com/hazelcast/hazelcast-cpp-client/archive/v4.0.0.tar.gz
I believe it shouldn't. There are others ways to download the library and I wouldn't want to it crowd the requirements part with too many things. Any user who doesn't have curl installed can install it if the command fails.

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +The install command may require administrator privileges depending on your install prefix.
Added a sentence stating that the user should make sure to pass the same `--config` parameter to both commands.

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +cmake .. -DWITH_OPENSSL=ON -DBUILD_SHARED_LIB=OFF -DBUILD_STATIC_LIB=ON
Yes ?

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +cmake .. -DWITH_OPENSSL=ON -DBUILD_SHARED_LIB=OFF -DBUILD_STATIC_LIB=ON
This section isn't for building the examples.

2021-01-18 14:33 UTC, yemreinci commented on README.md
> +cmake -G "Visual Studio 16 2019" .. -DCMAKE_INSTALL_PREFIX=C:\HazelcastCxx
They are removed.

2021-01-18 14:50 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-18 15:04 UTC, ihsandemir requested changes

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +### 1.1.3. Linux and MacOS users
```suggestion
### 1.1.3. Linux and MacOS Users
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +### 1.1.4. Windows users
```suggestion
### 1.1.4. Windows Users
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +### 1.1.5. Advanced installation
```suggestion
### 1.1.5. Advanced Installation
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +#### 1.1.5.1. Custom install location
```suggestion
#### 1.1.5.1. Custom Install Location
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +#### 1.1.5.2. CMake configuration
```suggestion
#### 1.1.5.2. CMake Configuration
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +##### Example configuration commands
```suggestion
##### 1.1.5.2.1 Example Configuration Commands
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +#### 1.3.1. CMake users
```suggestion
#### 1.3.1. CMake Users
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +#### 1.3.2. Linux and MacOS users
```suggestion
#### 1.3.2. Linux and MacOS Users
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +#### 1.3.3. Windows users
```suggestion
#### 1.3.3. Windows Users
```

2021-01-18 15:04 UTC, ihsandemir commented on README.md
> +    * [1.1.5. Advanced installation](#115-advanced-installation)
Will you add subsections 1.1.5.1 and 1.1.5.2 to ToC?

2021-01-18 16:18 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-18 17:29 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-18 17:41 UTC, devOpsHazelcast commented
Linux test FAILed.

2021-01-18 17:42 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-18 17:53 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-18 18:05 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-18 18:17 UTC, devOpsHazelcast commented
Linux test PASSed.

2021-01-18 18:19 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-18 18:30 UTC, ihsandemir approved these changes

2021-01-18 18:56 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-18 19:33 UTC, devOpsHazelcast commented
Windows test PASSed.

2021-01-18 21:24 UTC, merged